#!/usr/bin/env Rscript
# Assembles combo/ (a plain R package, jamovi's source format) from the
# submodules listed in modules.yaml. Wipes and rebuilds combo/ from scratch
# every run, so it is never a source of truth -- it's gitignored.
#
# What gets merged and how:
#   R/*.b.R + other helper .R  -> copied flat into combo/R (name collision = error)
#   jamovi/*.a.yaml/.r.yaml/.u.yaml/js/*.js -> copied into combo/jamovi (collision = error)
#   jamovi/00refs.yaml `refs:` -> merged by key
#   jamovi/i18n/<locale>.po    -> merged per locale with `msgcat --use-first`
#   data/*.csv                 -> copied into combo/data (collision = error)
#   DESCRIPTION Imports:       -> unioned by bare package name
#   NAMESPACE import()/importFrom() lines -> unioned
# NOT touched: .h.R, 00jmv.R, jamovi/0000.yaml -- jmvtools::prepare() (run by
# tools/install.sh) regenerates those from the merged R/ and jamovi/ above.
suppressPackageStartupMessages(library(yaml))

script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
script_path <- sub("^--file=", "", script_arg)
root <- normalizePath(file.path(dirname(script_path), ".."))
combo <- file.path(root, "combo")

cfg <- yaml::read_yaml(file.path(root, "modules.yaml"))$modules

unlink(combo, recursive = TRUE)
dir.create(file.path(combo, "R"), recursive = TRUE)
dir.create(file.path(combo, "jamovi", "i18n"), recursive = TRUE)
dir.create(file.path(combo, "jamovi", "js"), recursive = TRUE)
dir.create(file.path(combo, "data"), recursive = TRUE)

copy_flat <- function(files, dest_dir, label) {
  for (f in files) {
    dest <- file.path(dest_dir, basename(f))
    if (file.exists(dest)) {
      stop(sprintf(
        "collision: %s already provided by another module (copying %s) -- rename it in its source repo",
        label, f
      ))
    }
    file.copy(f, dest)
  }
}

imports <- list()   # bare pkg name -> full "pkg (>= x)" string
ns_lines <- character(0)
refs <- list()
po_by_locale <- list()

for (m in cfg) {
  pkgdir <- file.path(root, m$repo, m$pkg)
  if (!dir.exists(pkgdir)) stop(sprintf("missing package dir: %s", pkgdir))
  cat(sprintf(">> %s (%s)\n", m$pkg, m$repo))

  r_files <- list.files(file.path(pkgdir, "R"), full.names = TRUE)
  r_files <- r_files[!grepl("\\.h\\.R$", r_files) & basename(r_files) != "00jmv.R"]
  copy_flat(r_files, file.path(combo, "R"), "R/")

  jm <- file.path(pkgdir, "jamovi")
  a_files <- list.files(jm, pattern = "\\.(a|r|u)\\.yaml$", full.names = TRUE)
  copy_flat(a_files, file.path(combo, "jamovi"), "jamovi/")

  js_files <- list.files(file.path(jm, "js"), full.names = TRUE)
  if (length(js_files)) copy_flat(js_files, file.path(combo, "jamovi", "js"), "jamovi/js/")

  data_files <- list.files(file.path(pkgdir, "data"), full.names = TRUE)
  if (length(data_files)) copy_flat(data_files, file.path(combo, "data"), "data/")

  refs_file <- file.path(jm, "00refs.yaml")
  if (file.exists(refs_file)) {
    mrefs <- yaml::read_yaml(refs_file)$refs
    for (key in names(mrefs)) {
      if (key %in% names(refs) && !identical(refs[[key]], mrefs[[key]])) {
        warning(sprintf("00refs.yaml: key '%s' differs between modules, keeping first", key))
        next
      }
      refs[[key]] <- mrefs[[key]]
    }
  }

  po_files <- list.files(file.path(jm, "i18n"), pattern = "\\.po$", full.names = TRUE)
  for (po in po_files) {
    locale <- sub("\\.po$", "", basename(po))
    po_by_locale[[locale]] <- c(po_by_locale[[locale]], po)
  }

  desc <- read.dcf(file.path(pkgdir, "DESCRIPTION"), fields = "Imports")[1, 1]
  if (!is.na(desc)) {
    for (part in strsplit(desc, ",")[[1]]) {
      part <- trimws(gsub("\\s+", " ", part))
      if (!nzchar(part)) next
      bare <- sub("^([A-Za-z0-9._]+).*$", "\\1", part)
      if (is.null(imports[[bare]]) || (!grepl(">=", imports[[bare]]) && grepl(">=", part))) {
        imports[[bare]] <- part
      }
    }
  }

  ns <- readLines(file.path(pkgdir, "NAMESPACE"), warn = FALSE)
  ns_lines <- c(ns_lines, grep("^(import|importFrom)\\(", ns, value = TRUE))
}

# -- DESCRIPTION: template + merged Imports -----------------------------------
desc_lines <- readLines(file.path(root, "template", "DESCRIPTION"))
imp_names <- sort(names(imports))
imp_entries <- paste0("    ", vapply(imp_names, function(n) imports[[n]], ""))
imp_entries[-length(imp_entries)] <- paste0(imp_entries[-length(imp_entries)], ",")
imp_block <- c("Imports:", imp_entries)
writeLines(c(desc_lines, imp_block), file.path(combo, "DESCRIPTION"))

# -- NAMESPACE: header + merged import lines + wildcard export ---------------
ns_out <- c(
  "# Generated by tools/assemble.R -- do not hand-edit, do not roxygenise().",
  "# jamovi reaches analyses via namespace[[name..Class]], bypassing exports;",
  "# exportPattern below exists only so each analysis is callable from plain R.",
  sort(unique(ns_lines)),
  'exportPattern("^[[:alpha:]]+")'
)
writeLines(ns_out, file.path(combo, "NAMESPACE"))

# -- 00refs.yaml ---------------------------------------------------------------
if (length(refs)) {
  yaml::write_yaml(list(refs = refs), file.path(combo, "jamovi", "00refs.yaml"))
}

# -- i18n: merge each locale's .po files across modules ------------------------
if (length(po_by_locale) && Sys.which("msgcat") == "") {
  stop("msgcat not found (brew install gettext) -- needed to merge jamovi/i18n/*.po")
}
for (locale in names(po_by_locale)) {
  out <- file.path(combo, "jamovi", "i18n", paste0(locale, ".po"))
  status <- system2("msgcat", c("--use-first", "-o", out, po_by_locale[[locale]]))
  if (status != 0) stop(sprintf("msgcat failed merging locale '%s'", locale))
}

cat(sprintf(
  "\n>> assembled combo/: %d analyses, %d R files, %d Imports, %d locales\n",
  length(list.files(file.path(combo, "jamovi"), pattern = "\\.a\\.yaml$")),
  length(list.files(file.path(combo, "R"))),
  length(imp_names),
  length(po_by_locale)
))
